name: routix_flutter_example
description: Demonstrates how to use the routix_flutter plugin.
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  routix_flutter:
    path: ../
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
